FoodProject/FoodProject/Models/Food.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Models
{
    public class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public int Stock { get; set; }
        public int CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

FoodProject/FoodProject/Controllers/FoodController.cs
using FoodProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace FoodProject.Controllers
{
    public class FoodController : Controller
    {
        FoodRepository foodRepository = new FoodRepository();
        Context c = new Context();
        public IActionResult Index(int page=1)
        {
           
            return View(foodRepository.TList("Category").ToPagedList(page,10));  // Category tablosundan ihtiyacımız olan veriyi çekmek için Inculede metodunu kullandığımız için
            // Burada listelerden Category tablosununda listelenmesini sağladık. ToPadegList ile sayfalama işlemi yaptık.
        }

        [HttpGet]
        public IActionResult FoodAdd()
        {
            List<SelectListItem> kategori = (from i in c.Categories.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.CategoryName,
                                                 Value = i.CategoryID.ToString()

                                             }).ToList();

            ViewBag.ktg = kategori;
            return View();
        }
        [HttpPost]

        public IActionResult FoodAdd(Food p)
        {
            foodRepository.TAdd(p);
            return RedirectToAction("Index");

        }
        public IActionResult FoodDelete(int id)
        {

            foodRepository.TDelete(new Food { FoodID = id }); // AspNet'teki context sınıfından nesne türeterek yaptığımız işlemi de kullanabiliriz
                                                              // bu yöntemi de kullanabiliriz. İki yöntemde silme işlemini gerçekleştirir.

            return RedirectToAction("Index"); 
        }

        [HttpGet]
        public IActionResult FoodUpdate(int id)
        {
     
            List<SelectListItem> deger = (from i in c.Categories.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.CategoryName,
                                              Value = i.CategoryID.ToString()

                                          }).ToList();


            ViewBag.dgr = deger;
            var get = foodRepository.TGet(id);
            return View(get);
        }
        [HttpPost]
        public IActionResult FoodUpdate(Food p)
        {
            foodRepository.TUpdate(p);

            return RedirectToAction("Index");
        }



    }
}

FoodProject/FoodProject/Views/Food/FoodAdd.cshtml
@model FoodProject.Models.Food
@{
    ViewData["Title"] = "FoodAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yiyecek Ekleme Sayfası</h1>

@using (Html.BeginForm("FoodAdd", "Food", FormMethod.Post))
{

    @Html.Label("Yiyecek Adı")
    @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control", placeholder = "Yiyecek Adı" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control", placeholder = "Fiyat" })
    <br />
    @Html.Label("Stok Miktarı")
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control", placeholder = "Stok Miktarı" })
    <br />
    @Html.Label("Resim")
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control", placeholder = "Resim Yolu" })
    <br />

    @Html.Label("Kategorisi")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.ktg, new { @class = "form-control" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control", placeholder = "Açıklama" })
    <br />


    <button class="btn btn-primary"> Ekle</button>

}

FoodProject/FoodProject/Views/Food/FoodUpdate.cshtml
@model FoodProject.Models.Food
@{
    ViewData["Title"] = "FoodUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    @Html.HiddenFor(x => x.FoodID)
    @Html.Label("Yiyecek Adı")
    @Html.TextBoxFor(x => x.FoodName, "", new { @class = "form-control" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Price, "", new { @class = "form-control" })
    <br />
    @Html.Label("Stok")
    @Html.TextBoxFor(x => x.Stock, "", new { @class = "form-control" })
    <br />
    @Html.Label("Resim URL")
    @Html.TextBoxFor(x => x.ImageURL, "", new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")  
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    @Html.Label("Açıklama")
   @Html.TextAreaFor(x=> x.Description,new {@class="form-control" })
    <br />

    <button class="btn btn-success btn-sm">Kaydet </button>



}

FoodProject/FoodProject/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core

@model PagedList<FoodProject.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<table class="table table-bordered">
    <thead style="background-color: #1abc9c; color: white;">
        <tr>
            <th> ID </th>
            <th> Yiyecek Adı </th>
            <th> Fiyatı</th>
            <th> Stok Miktarı</th>
            <th> Yiyecek Kategorisi </th>
            <th> SİL</th>
            <th> GÜNCELLE </th>
            <th> DETAYLAR </th>

        </tr>
        </thead>
        @foreach (var item in Model)
        {
            

            <tr>
                <td>@item.FoodID </td>
                <td>@item.FoodName </td>
                <td> @item.Price</td>
                @{ 

                    string renk = "";
                    string durum = "";

                    if (item.Stock<=100)
                    {
                        renk = "text-danger";
                        durum = "Çok Kötü";
                    }
                    if (item.Stock>100 && item.Stock<=200)
                    {
                        renk = "text-warning";
                        durum = "Kötü";
                    }
                    if (item.Stock>200 && item.Stock<=400)
                    {
                        renk = "text-info";
                        durum = "İyi";
                    }
                    if (item.Stock>400 )
                    {
                        renk = "text-success";
                        durum = "Çok İyi ";
                    }
                }

                <td class="@renk">@item.Stock (@durum) </td>


                <td>@item.Category.CategoryName </td>
                <td> <a href="/Food/FoodDelete/@item.FoodID" class="btn btn-light btn-sm" style="background-color:#c0392b; color:white;"><i class="fa-solid fa-trash-can-arrow-up"></i> SİL</a> </td>
                <td> <a href="/Food/FoodUpdate/@item.FoodID" class="btn btn-light btn-sm" style="background-color: #16a085; color:white;"><i class="fa-solid fa-arrows-rotate"></i> GÜNCELLE</a> </td>
                <td> <a href="#" class="btn btn-light btn-sm" style="background-color: #f39c12; color: white;"><i class="fa-solid fa-grip"></i> DETAY GÖR</a> </td>

            </tr>

        }


</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page }))  <!-- Sayfanın altındaki (1-2-3 vs..) yazılar için gerekli kod satırı
                                                                               page kısmı Index IActionResult'undaki parametre ile aynı olmalıdır.-->
<a href="/Food/FoodAdd/" class="btn btn-primary"> Yeni Yiyecek Ekle </a>