FoodProject/FoodProject/Controllers/ChartController.cs
using FoodProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    
    public class ChartController : Controller
    {
        
           public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult Index3()
        {
            return View();
        }

        public IActionResult VisualizeProductResult2() // Ürün sonuçlarını görselleştir.
        {
            return Json(FoodList()); 

        }
        public List<Class2> FoodList()
        {
            List<Class2> cs2 = new List<Class2>();
            using (var c = new Context())
            {
                cs2 = c.Foods.Select(x => new Class2
                {
                    FoodName = x.FoodName,
                    Stock = x.Stock

                }).ToList();
            
            }
            return cs2;
        }


        public IActionResult VisualizeProductResult() // Ürün sonuçlarını görselleştir.
        {
            return Json(ProList()); 

        }


        public List<Class1> ProList()
        {
            List<Class1> cs = new List<Class1>();
            cs.Add(new Class1()
            {

                proname ="Computer",
                stock=150
            });

             cs.Add(new Class1()
            {

                proname = "LCD",
                stock=75
            });

             cs.Add(new Class1()
            {

                proname = "USB Disk",
                stock=350
            });

            return cs; 

        }


   

        
    }
}

FoodProject/FoodProject/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.proname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
    <a href="/Chart/Index2/" class="btn btn-warning" style="margin-bottom:100px; float:right; margin-left:10px;"> Column Charts Show </a>
    <a href="/Chart/Index3/" class="btn btn-danger" style="margin-bottom: 100px; float: right;" > Dynamic Google Charts Show </a>
</body>
</html>

FoodProject/FoodProject/Views/Chart/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.proname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnChart_Div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnChart_Div"></div>
</body>
</html>

FoodProject/FoodProject/Views/Chart/Index3.cshtml
@{
    ViewData["Title"] = "Index3";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food-Stok Grafiği",
                width: 1000,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>